// <auto-generated />
using System;
using GlucoKids.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlucoKids.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523225756_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlucoKids.Domain.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconEmoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("achievements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Lessons",
                            Description = "Заверши свій перший урок",
                            IconEmoji = "📖",
                            Key = "first_lesson",
                            Title = "Перший урок",
                            XpReward = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "Lessons",
                            Description = "Заверши 5 уроків",
                            IconEmoji = "🎓",
                            Key = "lessons_5",
                            Title = "5 уроків",
                            XpReward = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "Lessons",
                            Description = "Заверши всі уроки програми",
                            IconEmoji = "🏆",
                            Key = "all_lessons",
                            Title = "Всі уроки",
                            XpReward = 200
                        },
                        new
                        {
                            Id = 4,
                            Category = "Glucose",
                            Description = "Збережи свій перший запис глюкози",
                            IconEmoji = "🩸",
                            Key = "first_record",
                            Title = "Перший запис",
                            XpReward = 10
                        },
                        new
                        {
                            Id = 5,
                            Category = "Glucose",
                            Description = "Збережи 7 записів глюкози",
                            IconEmoji = "📊",
                            Key = "records_7",
                            Title = "7 записів",
                            XpReward = 30
                        },
                        new
                        {
                            Id = 6,
                            Category = "Glucose",
                            Description = "Збережи 30 записів глюкози",
                            IconEmoji = "📈",
                            Key = "records_30",
                            Title = "30 записів",
                            XpReward = 100
                        },
                        new
                        {
                            Id = 7,
                            Category = "Glucose",
                            Description = "5 показників у цільовому діапазоні",
                            IconEmoji = "✅",
                            Key = "in_range_5",
                            Title = "У нормі",
                            XpReward = 50
                        },
                        new
                        {
                            Id = 8,
                            Category = "Battle",
                            Description = "Виграй свій перший батл",
                            IconEmoji = "⚔️",
                            Key = "first_win",
                            Title = "Перша перемога",
                            XpReward = 20
                        },
                        new
                        {
                            Id = 9,
                            Category = "Battle",
                            Description = "Виграй 5 батлів",
                            IconEmoji = "🥇",
                            Key = "wins_5",
                            Title = "5 перемог",
                            XpReward = 75
                        },
                        new
                        {
                            Id = 10,
                            Category = "Battle",
                            Description = "Виграй 10 батлів",
                            IconEmoji = "👑",
                            Key = "wins_10",
                            Title = "10 перемог",
                            XpReward = 150
                        },
                        new
                        {
                            Id = 11,
                            Category = "Streak",
                            Description = "Роби записи 3 дні підряд",
                            IconEmoji = "🔥",
                            Key = "streak_3",
                            Title = "3 дні поспіль",
                            XpReward = 20
                        },
                        new
                        {
                            Id = 12,
                            Category = "Streak",
                            Description = "Роби записи 7 днів підряд",
                            IconEmoji = "⚡",
                            Key = "streak_7",
                            Title = "Тижневий стрік",
                            XpReward = 50
                        },
                        new
                        {
                            Id = 13,
                            Category = "Streak",
                            Description = "Роби записи 30 днів підряд",
                            IconEmoji = "💎",
                            Key = "streak_30",
                            Title = "Місячний стрік",
                            XpReward = 200
                        });
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.ChildAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("ChildId", "AchievementId")
                        .IsUnique();

                    b.ToTable("child_achievements", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Duel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengerChildId")
                        .HasColumnType("integer");

                    b.Property<int>("ChallengerId")
                        .HasColumnType("integer");

                    b.Property<int>("ChallengerPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DuelDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpponentChildId")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentId")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerChildId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerId");

                    b.HasIndex("OpponentId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Duel");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.DuelPointEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuelId")
                        .HasColumnType("integer");

                    b.Property<int?>("GlucoseReadingId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("DuelId");

                    b.HasIndex("GlucoseReadingId");

                    b.ToTable("DuelPointEvent");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.FoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<decimal>("CarbohydratesG")
                        .HasColumnType("numeric(7,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("HealthRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("WeightG")
                        .HasColumnType("numeric(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.ToTable("food_entries", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.GlucoseReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DuelId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("DuelId");

                    b.ToTable("glucose_readings", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.HealthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CarbohydratesG")
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("GlucoseMmol")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("InsulinLong")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("InsulinShort")
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("MealContext")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Mood")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("health_records", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.LessonProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LessonKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "LessonKey")
                        .IsUnique();

                    b.ToTable("lesson_progress", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.MedicalProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("DiabetesType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly?>("DiagnosedAt")
                        .HasColumnType("date");

                    b.Property<string>("InsulinBrand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TargetGlucoseMax")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("TargetGlucoseMin")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.ToTable("medical_profiles", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.XpLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("xp_logs", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Child", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.User", "User")
                        .WithOne("Child")
                        .HasForeignKey("GlucoKids.Domain.Entities.Child", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.ChildAchievement", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Achievement", "Achievement")
                        .WithMany("ChildAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Duel", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Challenger")
                        .WithMany()
                        .HasForeignKey("ChallengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.Child", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.Child", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Challenger");

                    b.Navigation("Opponent");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.DuelPointEvent", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.Duel", "Duel")
                        .WithMany("PointEvents")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.GlucoseReading", "GlucoseReading")
                        .WithMany()
                        .HasForeignKey("GlucoseReadingId");

                    b.Navigation("Child");

                    b.Navigation("Duel");

                    b.Navigation("GlucoseReading");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.FoodEntry", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.HealthRecord", "HealthRecord")
                        .WithMany("Foods")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.GlucoseReading", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.Duel", "Duel")
                        .WithMany("GlucoseReadings")
                        .HasForeignKey("DuelId");

                    b.Navigation("Child");

                    b.Navigation("Duel");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.HealthRecord", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.LessonProgress", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany("Progress")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.MedicalProfile", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithOne("MedicalProfile")
                        .HasForeignKey("GlucoKids.Domain.Entities.MedicalProfile", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.XpLog", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany("XpLogs")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("ChildAchievements");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Child", b =>
                {
                    b.Navigation("MedicalProfile");

                    b.Navigation("Progress");

                    b.Navigation("XpLogs");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Duel", b =>
                {
                    b.Navigation("GlucoseReadings");

                    b.Navigation("PointEvents");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.HealthRecord", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.User", b =>
                {
                    b.Navigation("Child");
                });
#pragma warning restore 612, 618
        }
    }
}
