// <auto-generated />
using System;
using GlucoKids.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlucoKids.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlucoKids.Domain.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.ChildStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<int>("Draws")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDuels")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("WinStreak")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.ToTable("child_stats", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Duel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengerChildId")
                        .HasColumnType("integer");

                    b.Property<int>("ChallengerPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("DuelDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpponentChildId")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("WinnerChildId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerChildId");

                    b.HasIndex("OpponentChildId");

                    b.HasIndex("WinnerChildId");

                    b.ToTable("duels", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.DuelPointEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DuelId")
                        .HasColumnType("integer");

                    b.Property<int?>("GlucoseReadingId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("DuelId");

                    b.HasIndex("GlucoseReadingId");

                    b.ToTable("duel_point_events", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.GlucoseReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DuelId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("DuelId");

                    b.ToTable("glucose_readings", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.HealthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CarbohydratesG")
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("GlucoseMmol")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("InsulinLong")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("InsulinShort")
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("MealContext")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Mood")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("health_records", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.LessonProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("ChildId", "LessonId")
                        .IsUnique();

                    b.ToTable("lesson_progress", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.MatchmakingQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.ToTable("matchmaking_queue", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("parents", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.ParentChildLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime?>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("parent_child_links", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.PsychoLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("psycho_lessons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModuleId = 1,
                            OrderIndex = 1,
                            Title = "Що таке глюкоза?"
                        },
                        new
                        {
                            Id = 2,
                            ModuleId = 1,
                            OrderIndex = 2,
                            Title = "Типи діабету"
                        },
                        new
                        {
                            Id = 3,
                            ModuleId = 1,
                            OrderIndex = 3,
                            Title = "Як працює інсулін?"
                        },
                        new
                        {
                            Id = 4,
                            ModuleId = 2,
                            OrderIndex = 1,
                            Title = "Що таке глюкометр?"
                        },
                        new
                        {
                            Id = 5,
                            ModuleId = 2,
                            OrderIndex = 2,
                            Title = "Коли вимірювати глюкозу?"
                        },
                        new
                        {
                            Id = 6,
                            ModuleId = 2,
                            OrderIndex = 3,
                            Title = "Норми рівня глюкози"
                        },
                        new
                        {
                            Id = 7,
                            ModuleId = 3,
                            OrderIndex = 1,
                            Title = "Що таке хлібна одиниця?"
                        },
                        new
                        {
                            Id = 8,
                            ModuleId = 3,
                            OrderIndex = 2,
                            Title = "Продукти з низьким глікемічним індексом"
                        },
                        new
                        {
                            Id = 9,
                            ModuleId = 3,
                            OrderIndex = 3,
                            Title = "Як читати етикетки продуктів?"
                        },
                        new
                        {
                            Id = 10,
                            ModuleId = 4,
                            OrderIndex = 1,
                            Title = "Чому спорт корисний при діабеті?"
                        },
                        new
                        {
                            Id = 11,
                            ModuleId = 4,
                            OrderIndex = 2,
                            Title = "Що взяти з собою на тренування?"
                        },
                        new
                        {
                            Id = 12,
                            ModuleId = 4,
                            OrderIndex = 3,
                            Title = "Гіпоглікемія під час активності"
                        });
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.PsychoModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("psycho_modules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Основи про діабет для дітей",
                            OrderIndex = 1,
                            Title = "Що таке цукровий діабет?"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Навчання користуватись глюкометром",
                            OrderIndex = 2,
                            Title = "Як вимірювати рівень глюкози?"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Хлібні одиниці та збалансована дієта",
                            OrderIndex = 3,
                            Title = "Правильне харчування"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Спорт і діабет — як поєднати?",
                            OrderIndex = 4,
                            Title = "Фізична активність"
                        });
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Child", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.User", "User")
                        .WithOne("Child")
                        .HasForeignKey("GlucoKids.Domain.Entities.Child", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.ChildStats", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Duel", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Challenger")
                        .WithMany()
                        .HasForeignKey("ChallengerChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.Child", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.Child", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerChildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Challenger");

                    b.Navigation("Opponent");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.DuelPointEvent", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.Duel", "Duel")
                        .WithMany("PointEvents")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.GlucoseReading", "GlucoseReading")
                        .WithMany()
                        .HasForeignKey("GlucoseReadingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("Duel");

                    b.Navigation("GlucoseReading");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.GlucoseReading", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.Duel", "Duel")
                        .WithMany("GlucoseReadings")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("Duel");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.HealthRecord", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.LessonProgress", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany("Progress")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.PsychoLesson", "Lesson")
                        .WithMany("Progress")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.MatchmakingQueue", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Parent", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.User", "User")
                        .WithOne("Parent")
                        .HasForeignKey("GlucoKids.Domain.Entities.Parent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.ParentChildLink", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.User", "ChildUser")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlucoKids.Domain.Entities.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildUser");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.PsychoLesson", b =>
                {
                    b.HasOne("GlucoKids.Domain.Entities.PsychoModule", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Child", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.Duel", b =>
                {
                    b.Navigation("GlucoseReadings");

                    b.Navigation("PointEvents");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.PsychoLesson", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.PsychoModule", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("GlucoKids.Domain.Entities.User", b =>
                {
                    b.Navigation("Child");

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
